ayaline_composer:
    resource: "@AyalineComposerBundle/Resources/config/routing.yml"
    prefix:   /

lopi_pusher:
    resource: "@LopiPusherBundle/Resources/config/routing.xml"
    prefix:   /pusher

_monitor:
    resource: "@LiipMonitorBundle/Resources/config/routing.yml"
    prefix: /monitor/health